version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./dockerfile
    ports:
      - "8081:8081"
      - "8080:8080"
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"
      - "4318:4318"
